In [2]:
from itertools import permutations
import pandas as pd

def generate_matchups(teams_df):
 
    teams = teams_df["name"].tolist()
    matchups = list(permutations(teams, 2)) 

    match_df = pd.DataFrame(matchups, columns=["team1", "team2"])
    return match_df

qualified_teams = pd.read_csv("qualified.csv")
match_df = generate_matchups(qualified_teams)
match_df.head()

  team1 team2
0   RUS   KSA
1   RUS   EGY
2   RUS   URU
3   RUS   POR
4   RUS   ESP

In [3]:
import pandas as pd
def map_team_features(match_df, team_stats):

    team1_stats = team_stats.drop_duplicates(subset=["team1"]).set_index("team1")
    team2_stats = team_stats.drop_duplicates(subset=["team2"]).set_index("team2")  

    team1_stats = team1_stats.add_suffix("_team1")
    team2_stats = team2_stats.add_suffix("_team2")

    match_df = match_df.merge(team1_stats, left_on="team1", right_index=True, how="left")


    match_df = match_df.merge(team2_stats, left_on="team2", right_index=True, how="left")

    match_df["team1Home"] = match_df["team1"] == "RUS"
    match_df["team2Home"] = match_df["team2"] == "RUS"
    match_df["neutralVenue"] = ~(match_df["team1Home"] | match_df["team2Home"])
    match_df["friendly"] = False
    match_df["qualifier"] = False
    match_df["finaltourn"] = True

    required_columns = [
        "team1", "team2", "team1Home", "team2Home", "neutralVenue", "friendly", "qualifier", "finaltourn", "team1_win_rate_10_team1", 
        "team1_loss_rate_10_team1", "team1_draw_rate_10_team1", "team1_goal_diff_avg_10_team1",
        "team1_confed_form_10_team1", "team1_win_rate_20_team1", "team1_loss_rate_20_team1",
        "team1_draw_rate_20_team1", "team1_goal_diff_avg_20_team1", "team1_confed_form_20_team1",
        "team1_win_rate_30_team1", 
        "team1_loss_rate_30_team1", "team1_draw_rate_30_team1", "team1_goal_diff_avg_30_team1",
        "team1_confed_form_30_team1", "team1_win_rate_40_team1", "team1_loss_rate_40_team1",
        "team1_draw_rate_40_team1", "team1_goal_diff_avg_40_team1", "team1_confed_form_40_team1",
        "team1_win_rate_50_team1", 
        "team1_loss_rate_50_team1", "team1_draw_rate_50_team1", "team1_goal_diff_avg_50_team1",
        "team1_confed_form_50_team1",
        
        "team2_win_rate_10_team2", "team2_loss_rate_10_team2", "team2_draw_rate_10_team2",
        "team2_goal_diff_avg_10_team2", "team2_confed_form_10_team2", "team2_win_rate_20_team2",
        "team2_loss_rate_20_team2", "team2_draw_rate_20_team2", "team2_goal_diff_avg_20_team2",
        "team2_confed_form_20_team2",
        "team2_win_rate_30_team2", "team2_loss_rate_30_team2", "team2_draw_rate_30_team2",
        "team2_goal_diff_avg_30_team2", "team2_confed_form_30_team2", "team2_win_rate_40_team2",
        "team2_loss_rate_40_team2", "team2_draw_rate_40_team2", "team2_goal_diff_avg_40_team2",
        "team2_confed_form_40_team2",
        "team2_win_rate_50_team2", "team2_loss_rate_50_team2", "team2_draw_rate_50_team2",
        "team2_goal_diff_avg_50_team2", "team2_confed_form_50_team2"
    ]


    rename_columns = {col: col.replace("_team1_team1", "_team1").replace("_team2_team2", "_team2") for col in match_df.columns}
    match_df = match_df.rename(columns=rename_columns)

   
    match_df = match_df[required_columns]

    return match_df
df=pd.read_csv('updated2.csv')
df = df.sort_values(by="date", ascending=False)
match_df = map_team_features(match_df, df)
match_df.head()

,team1,team2,team1Home,team2Home,neutralVenue,friendly,qualifier,finaltourn,team1_win_rate_10_team1,team1_loss_rate_10_team1,...,team2_win_rate_40_team2,team2_loss_rate_40_team2,team2_draw_rate_40_team2,team2_goal_diff_avg_40_team2,team2_confed_form_40_team2,team2_win_rate_50_team2,team2_loss_rate_50_team2,team2_draw_rate_50_team2,team2_goal_diff_avg_50_team2,team2_confed_form_50_team2
0,RUS,KSA,True,False,False,False,False,True,0.6,0.3,...,0.325,0.375,0.300,0.350,0.325,0.32,0.42,0.26,0.36,0.28
1,RUS,EGY,True,False,False,False,False,True,0.6,0.3,...,0.450,0.350,0.200,-0.175,0.375,0.38,0.36,0.26,0.02,0.36
2,RUS,URU,True,False,False,False,False,True,0.6,0.3,...,0.450,0.375,0.175,-0.200,0.425,0.42,0.34,0.24,-0.14,0.46
3,RUS,POR,True,False,False,False,False,True,0.6,0.3,...,0.225,0.600,0.175,0.650,0.225,0.22,0.58,0.20,0.64,0.22
4,RUS,ESP,True,False,False,False,False,True,0.6,0.3,...,0.075,0.750,0.175,1.425,0.100,0.10,0.70,0.20,1.26,0.08

In [4]:
match_df['friendly']=0
match_df['qualifier']=0
match_df['team1Home']=0
match_df['team2Home']=0
match_df['neutralVenue']=1
match_df['finaltourn']=1
match_df.head()

,team1,team2,team1Home,team2Home,neutralVenue,friendly,qualifier,finaltourn,team1_win_rate_10_team1,team1_loss_rate_10_team1,...,team2_win_rate_40_team2,team2_loss_rate_40_team2,team2_draw_rate_40_team2,team2_goal_diff_avg_40_team2,team2_confed_form_40_team2,team2_win_rate_50_team2,team2_loss_rate_50_team2,team2_draw_rate_50_team2,team2_goal_diff_avg_50_team2,team2_confed_form_50_team2
0,RUS,KSA,0,0,1,0,0,1,0.6,0.3,...,0.325,0.375,0.300,0.350,0.325,0.32,0.42,0.26,0.36,0.28
1,RUS,EGY,0,0,1,0,0,1,0.6,0.3,...,0.450,0.350,0.200,-0.175,0.375,0.38,0.36,0.26,0.02,0.36
2,RUS,URU,0,0,1,0,0,1,0.6,0.3,...,0.450,0.375,0.175,-0.200,0.425,0.42,0.34,0.24,-0.14,0.46
3,RUS,POR,0,0,1,0,0,1,0.6,0.3,...,0.225,0.600,0.175,0.650,0.225,0.22,0.58,0.20,0.64,0.22
4,RUS,ESP,0,0,1,0,0,1,0.6,0.3,...,0.075,0.750,0.175,1.425,0.100,0.10,0.70,0.20,1.26,0.08

In [5]:
match_df = match_df.rename(columns=lambda x: x.replace("_team1", "").replace("_team2", ""))
match_df.head()

,team1,team2,team1Home,team2Home,neutralVenue,friendly,qualifier,finaltourn,team1_win_rate_10,team1_loss_rate_10,...,team2_win_rate_40,team2_loss_rate_40,team2_draw_rate_40,team2_goal_diff_avg_40,team2_confed_form_40,team2_win_rate_50,team2_loss_rate_50,team2_draw_rate_50,team2_goal_diff_avg_50,team2_confed_form_50
0,RUS,KSA,0,0,1,0,0,1,0.6,0.3,...,0.325,0.375,0.300,0.350,0.325,0.32,0.42,0.26,0.36,0.28
1,RUS,EGY,0,0,1,0,0,1,0.6,0.3,...,0.450,0.350,0.200,-0.175,0.375,0.38,0.36,0.26,0.02,0.36
2,RUS,URU,0,0,1,0,0,1,0.6,0.3,...,0.450,0.375,0.175,-0.200,0.425,0.42,0.34,0.24,-0.14,0.46
3,RUS,POR,0,0,1,0,0,1,0.6,0.3,...,0.225,0.600,0.175,0.650,0.225,0.22,0.58,0.20,0.64,0.22
4,RUS,ESP,0,0,1,0,0,1,0.6,0.3,...,0.075,0.750,0.175,1.425,0.100,0.10,0.70,0.20,1.26,0.08

In [7]:

match_df.to_csv('sim.csv', index=False)

In [8]:
arg_bra_match = match_df[
    ((match_df["team1"] == "NGA") & (match_df["team2"] == "BRA"))
]
print(arg_bra_match)

    team1 team2  team1Home  team2Home  neutralVenue  friendly  qualifier  \
480   NGA   BRA          0          0             1         0          0

     finaltourn  team1_win_rate_10  team1_loss_rate_10  ...  \
480           1                0.8                 0.2  ...

     team2_win_rate_40  team2_loss_rate_40  team2_draw_rate_40  \
480              0.175                0.55               0.275

     team2_goal_diff_avg_40  team2_confed_form_40  team2_win_rate_50  \
480                    1.25                 0.275               0.18

     team2_loss_rate_50  team2_draw_rate_50  team2_goal_diff_avg_50  \
480                0.52                 0.3                    1.14

     team2_confed_form_50
480                  0.28

[1 rows x 58 columns]

In [9]:
import joblib
encoder = joblib.load('encoder.joblib')


arg_bra_match["team1"] = encoder.transform(arg_bra_match["team1"])
arg_bra_match["team2"] = encoder.transform(arg_bra_match["team2"])

arg_bra_match.head()

C:\Users\mKayy\AppData\Local\Temp\ipykernel_16040\1829450150.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arg_bra_match["team1"] = encoder.transform(arg_bra_match["team1"])
C:\Users\mKayy\AppData\Local\Temp\ipykernel_16040\1829450150.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  arg_bra_match["team2"] = encoder.transform(arg_bra_match["team2"])

,team1,team2,team1Home,team2Home,neutralVenue,friendly,qualifier,finaltourn,team1_win_rate_10,team1_loss_rate_10,...,team2_win_rate_40,team2_loss_rate_40,team2_draw_rate_40,team2_goal_diff_avg_40,team2_confed_form_40,team2_win_rate_50,team2_loss_rate_50,team2_draw_rate_50,team2_goal_diff_avg_50,team2_confed_form_50
480,136,28,0,0,1,0,0,1,0.8,0.2,...,0.175,0.55,0.275,1.25,0.275,0.18,0.52,0.3,1.14,0.28

In [10]:
import xgboost as xgb
import numpy as np
best_xgb = xgb.XGBClassifier()
best_xgb.load_model("best_xgb.json")
X_test = arg_bra_match
import numpy as np
def add_randomness(probabilities, noise_factor=0.05):

    noise = np.random.normal(0, noise_factor, probabilities.shape) 
    probabilities = probabilities + noise  
    probabilities = np.clip(probabilities, 0, 1)  
    probabilities /= probabilities.sum()  
    return probabilities

for i in range(99):
    prediction = best_xgb.predict(X_test)
    probabilities = best_xgb.predict_proba(X_test)[0]
    random_probs=add_randomness(probabilities)
    max_prob = np.max(random_probs) 
    max_index = np.argmax(random_probs)

    print(random_probs)

    if max_prob >= 0.5:
        pred=max_index
    else:
        pred=np.random.choice([0,1,2])
    outcome_map={0:'Draw', 1:'ARG', 2:'BRA'}
    print(outcome_map[pred])

[0.00819882 0.42421276 0.56758842]
BRA
[0.05140224 0.44981669 0.49878107]
ARG
[0.04850325 0.41851545 0.5329813 ]
BRA
[0.03298592 0.39037349 0.57664058]
BRA
[0.         0.46676404 0.53323596]
BRA
[0.         0.41916719 0.58083281]
BRA
[0.        0.4501321 0.5498679]
BRA
[0.07792501 0.44483307 0.47724192]
BRA
[0.         0.43176857 0.56823143]
BRA
[0.13357112 0.38815703 0.47827185]
ARG
[0.10257295 0.35077637 0.54665068]
BRA
[0.         0.43043152 0.56956848]
BRA
[0.02470379 0.42505323 0.55024298]
BRA
[0.04437349 0.44742993 0.50819659]
BRA
[0.         0.44040405 0.55959595]
BRA
[0.14871167 0.36260543 0.48868291]
BRA
[0.         0.43619902 0.56380098]
BRA
[0.06854678 0.42228    0.50917322]
BRA
[0.0184759  0.42762685 0.55389725]
BRA
[0.         0.39066053 0.60933947]
BRA
[0.         0.31562325 0.68437675]
BRA
[0.         0.43517193 0.56482807]
BRA
[0.         0.36419022 0.63580978]
BRA
[0.         0.49848906 0.50151094]
BRA
[0.         0.39181532 0.60818468]
BRA
[0.05630917 0.46136685 0.48232398]
Draw
[0.02618249 0.40958028 0.56423723]
BRA
[0.03404164 0.37905391 0.58690446]
BRA
[0.         0.39627233 0.60372767]
BRA
[0.05484614 0.38140107 0.56375279]
BRA
[0.         0.49981673 0.50018327]
BRA
[0.         0.45271295 0.54728705]
BRA
[0.         0.43024677 0.56975323]
BRA
[0.         0.41331789 0.58668211]
BRA
[0.02854777 0.4193902  0.55206203]
BRA
[0.         0.41893256 0.58106744]
BRA
[0.         0.44125472 0.55874528]
BRA
[0.         0.44137734 0.55862266]
BRA
[0.         0.42492313 0.57507687]
BRA
[0.05716182 0.35910416 0.58373402]
BRA
[0.02752372 0.41117298 0.5613033 ]
BRA
[0.01718881 0.48753313 0.49527806]
ARG
[0.         0.39394939 0.60605061]
BRA
[0.00282529 0.43786769 0.55930701]
BRA
[0.         0.46149757 0.53850243]
BRA
[0.        0.4471786 0.5528214]
BRA
[0.01467953 0.45720134 0.52811913]
BRA
[0.01571175 0.42300865 0.5612796 ]
BRA
[0.0278069 0.4768011 0.495392 ]
Draw
[0.         0.45004759 0.54995241]
BRA
[0.0331909  0.47007967 0.49672944]
Draw
[0.         0.38867781 0.61132219]
BRA
[0.02729885 0.47890416 0.49379699]
ARG
[0.         0.41151144 0.58848856]
BRA
[0.         0.50035769 0.49964231]
ARG
[0.02704995 0.38205593 0.59089412]
BRA
[0.02208912 0.42675447 0.55115641]
BRA
[0.         0.36335616 0.63664384]
BRA
[0.04039745 0.38614561 0.57345694]
BRA
[0.         0.40724482 0.59275518]
BRA
[0.05945439 0.39265371 0.5478919 ]
BRA
[0.         0.44526548 0.55473452]
BRA
[0.00595544 0.3908561  0.60318846]
BRA
[0.         0.44924268 0.55075732]
BRA
[0.        0.4501349 0.5498651]
BRA
[0.         0.44313993 0.55686007]
BRA
[0.         0.40099207 0.59900793]
BRA
[0.         0.40303827 0.59696173]
BRA
[0.         0.45634814 0.54365186]
BRA
[0.05725586 0.38516549 0.55757865]
BRA
[0.         0.45973559 0.54026441]
BRA
[0.         0.44057247 0.55942753]
BRA
[0.         0.44221273 0.55778727]
BRA
[0.         0.46355342 0.53644658]
BRA
[0.        0.3537888 0.6462112]
BRA
[0.         0.41260252 0.58739748]
BRA
[0.02164918 0.41560962 0.5627412 ]
BRA
[0.03217365 0.39320682 0.57461953]
BRA
[0.05520822 0.39822376 0.54656802]
BRA
[0.         0.46689865 0.53310135]
BRA
[0.01314365 0.50040276 0.48645359]
ARG
[0.00916441 0.35847777 0.63235781]
BRA
[0.04431308 0.38237723 0.57330969]
BRA
[0.09879559 0.42807623 0.47312818]
BRA
[0.         0.41330484 0.58669516]
BRA
[0.         0.46811713 0.53188287]
BRA
[0.         0.45521839 0.54478161]
BRA
[0.         0.44048955 0.55951045]
BRA
[0.01263995 0.41515234 0.57220771]
BRA
[0.         0.41967045 0.58032955]
BRA
[0.         0.39260049 0.60739951]
BRA
[0.         0.47804047 0.52195953]
BRA
[0.0573529  0.43894346 0.50370364]
BRA
[0.04612431 0.4944068  0.45946889]
ARG
[0.07806899 0.38404385 0.53788715]
BRA
[0.        0.4006849 0.5993151]
BRA
[0.05770029 0.38087352 0.56142618]
BRA
[0.        0.3945689 0.6054311]
BRA
[0.0386389  0.44909043 0.51227067]
BRA